### ISSUE TITLE
MoreCommands interfres with Nether rendering

### ISSUE THREAD

**Issue by jcotton42** [MrNobody98/morecommands#2]
# Versions:
MoreCommands: 1.4
MC: 1.7.10
MCP: 9.05
Forge: 10.13.4.1481
FML: 7.10.99.99
# Effects
When entering the Nether from the Overworld (and possibly the End), it does not render at all, and the player is stuck, shaking whenever they try to move. At this point saving and then loading the world drops the player into the nether, and it works just fine until they exit and reenter the Nether

**Comment by MrNobody98** [comment]
I really didn't notice that error -.- but I found the source and fixed it, just download it again, the links are the same as before
